version: "3.9"

services:
  traefik:
    ports:
      - 80:80

  # caddy:
  #   ports:
  #     - 80:80
  #     - 443:443

  temporal-web:
    image: temporalio/web
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/temporal-web.env
    networks:
      - todo-app
    depends_on:
      - temporal

  temporal-admin-tools:
    image: temporalio/admin-tools
    container_name: temporal-admin-tools
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/temporal-cli.env
    stdin_open: true
    tty: true
    networks:
      - todo-app
    depends_on:
      - temporal
