version: "3.9"

services:
  todo-app:
    build: ./frontend/todo-app
    image: todo-app
    ports:
      - 8000:80
    networks:
      - todo-net

  api-gateway:
    build: ./backend/api-gateway
    image: api-gateway
    restart: on-failure
    env_file:
      - ./env/api-gateway.env
    ports:
      - 8080:80
    networks:
      - todo-net

  todo-api:
    build: ./backend/todo-api
    image: todo-api
    restart: on-failure
    env_file:
      - ./env/todo-api.env
    ports:
      - 8081:8081
    networks:
      - todo-net
    depends_on:
      - db
      - nats

  todo-service:
    build: ./backend/todo-service
    image: todo-service
    restart: on-failure
    env_file:
      - ./env/todo-service.env
    networks:
      - todo-net
    depends_on:
      - db
      - nats

  notification-service:
    build: ./backend/notification-service
    image: notification-service
    restart: on-failure
    env_file:
      - ./env/notification-service.env
    networks:
      - todo-net
    depends_on:
      - nats

  db:
    image: postgres:13.2
    env_file:
      - ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db-vol:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-net

  nats:
    image: nats:2.2.2-alpine3.13
    ports:
      - 4222:4222
    networks:
      - todo-net

networks:
  todo-net:

volumes:
  db-vol:
