version: "3.9"

services:
  api-gateway:
    deploy:
      restart_policy:
        condition: any
    ports:
      - 443:443
    volumes:
      - /etc/todo-app/certs/:/etc/api-gateway/certs/:ro

  todo-app:
    deploy:
      restart_policy:
        condition: any

  todo-api:
    deploy:
      restart_policy:
        condition: any

  todo-service:
    deploy:
      restart_policy:
        condition: any

  notification-service:
    deploy:
      restart_policy:
        condition: any

  nats:
    deploy:
      restart_policy:
        condition: any

  db:
    deploy:
      restart_policy:
        condition: any

  minio:
    deploy:
      restart_policy:
        condition: any
    volumes:
      - minio:/data
      - /etc/todo-app/certs/:/root/.minio/certs/:ro

  loki:
    deploy:
      restart_policy:
        condition: any

  promtail:
    deploy:
      restart_policy:
        condition: any

  grafana:
    deploy:
      restart_policy:
        condition: any

  keycloak:
    deploy:
      restart_policy:
        condition: any
    ports:
      - 8443:8443
    volumes:
      - /etc/todo-app/certs/:/etc/x509/https/:ro
