version: "3.9"

services:
  api-gateway:
    deploy:
      restart_policy:
        condition: any
    ports:
      - 443:443
    secrets:
      - source: private.key
        target: /etc/api-gateway/certs/private.key
      - source: public.crt
        target: /etc/api-gateway/certs/public.crt

  todo-app:
    deploy:
      restart_policy:
        condition: any

  todo-api:
    deploy:
      restart_policy:
        condition: any

  todo-service:
    deploy:
      restart_policy:
        condition: any

  nats:
    deploy:
      restart_policy:
        condition: any

  centrifugo:
    deploy:
      restart_policy:
        condition: any

  db:
    deploy:
      restart_policy:
        condition: any

  minio:
    deploy:
      restart_policy:
        condition: any

  minio-console:
    deploy:
      restart_policy:
        condition: any
    ports:
      - 9443:9443
    secrets:
      - source: private.key
        target: /root/.console/certs/private.key
      - source: public.crt
        target: /root/.console/certs/public.crt

  loki:
    deploy:
      restart_policy:
        condition: any

  promtail:
    deploy:
      restart_policy:
        condition: any

  grafana:
    deploy:
      restart_policy:
        condition: any

  keycloak:
    deploy:
      restart_policy:
        condition: any
    ports:
      - 8443:8443
    secrets:
      - source: private.key
        target: /etc/x509/https/tls.key
      - source: public.crt
        target: /etc/x509/https/tls.crt

secrets:
  private.key:
    file: ./env/private.key
  public.crt:
    file: ./env/public.crt
