version: "3.9"

services:
  traefik:
    ports:
      - 80:80

  minio-console:
    ports:
      - 9090:9090

  keycloak:
    ports:
      - 8080:8080

  temporal-web:
    image: temporalio/web
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/temporal-web.env
    ports:
      - 8088:8088
    networks:
      - todo-app
    depends_on:
      - temporal

  temporal-admin-tools:
    image: temporalio/admin-tools
    container_name: temporal-admin-tools
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/temporal-cli.env
    stdin_open: true
    tty: true
    networks:
      - todo-app
    depends_on:
      - temporal
