version: "3.9"

services:
  api-gateway:
    build: ./backend/api-gateway
    image: todo-app/api-gateway
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/api-gateway.env
    ports:
      - 80:80
    networks:
      - backend

  todo-app:
    build: ./frontend
    image: todo-app/todo-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/todo-app.env
    networks:
      - backend

  todo-api:
    build: ./backend/todo-api
    image: todo-app/todo-api
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/todo-api.env
    networks:
      - backend
    depends_on:
      - db
      - nats-configure

  todo-service:
    build: ./backend/todo-service
    image: todo-app/todo-service
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/todo-service.env
    networks:
      - backend
    depends_on:
      - db
      - nats-configure

  notification-service:
    build: ./backend/notification-service
    image: todo-app/notification-service
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/notification-service.env
    networks:
      - backend
    depends_on:
      - nats
      - api-gateway

  nats:
    build: ./backend/nats/docker
    image: todo-app/nats
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/nats.env
    ports:
      - 4222:4222
    volumes:
      - nats:/nats
    networks:
      - backend

  nats-configure:
    build: ./backend/nats/jetstream
    image: todo-app/nats-configure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/nats.env
    networks:
      - backend
    depends_on:
      - nats

  db:
    build: ./backend/db/postgres
    image: todo-app/db
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  db-migrate:
    build: ./backend/db/migrate
    image: todo-app/db-migrate
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/migrate.env
    networks:
      - backend
    depends_on:
      - db

  minio:
    image: minio/minio
    deploy:
      restart_policy:
        condition: on-failure
    command: server /data
    env_file:
      - ./env/minio.env
    volumes:
      - minio:/data
    networks:
      - monitor

  minio-console:
    image: minio/console
    deploy:
      restart_policy:
        condition: on-failure
    command: server
    env_file:
      - ./env/minio-console.env
    ports:
      - 9090:9090
    networks:
      - monitor

  minio-migrate:
    build: ./monitor/minio/migrate
    image: todo-app/minio-migrate
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/minio.env
      - ./env/minio-migrate.env
    networks:
      - monitor
    depends_on:
      - minio

  loki:
    build: ./monitor/loki
    image: todo-app/loki
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/minio.env
      - ./env/loki.env
    networks:
      - monitor
    depends_on:
      - minio

  promtail:
    build: ./monitor/promtail
    image: todo-app/promtail
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/promtail.env
    volumes:
      - promtail:/tmp/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - monitor
      - backend
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/grafana.env
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - monitor
      - backend
    depends_on:
      - db

  grafana-configure:
    build: ./monitor/grafana
    image: todo-app/grafana-configure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/grafana-configure.env
    networks:
      - backend
    depends_on:
      - grafana

  keycloak:
    build: ./backend/keycloak/docker
    image: todo-app/keycloak
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/keycloak.env
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
  monitor:

volumes:
  db:
  nats:
  minio:
  grafana:
  promtail:
