http:
  routers:
    todo-app:
      entryPoints:
        - web
      service: todo-app
      rule: PathPrefix(`/`)

    todo-api:
      entryPoints:
        - web
      service: todo-api
      rule: PathPrefix(`/todos`)

    centrifugo:
      entryPoints:
        - web
      service: centrifugo
      rule: PathPrefix(`/connection`)

    grafana:
      entryPoints:
        - web
      service: grafana
      rule: PathPrefix(`/grafana`)

  services:
    todo-app:
      loadBalancer:
        servers:
          - url: http://todo-app

    todo-api:
      loadBalancer:
        servers:
          - url: http://todo-api

    centrifugo:
      loadBalancer:
        servers:
          - url: http://centrifugo:8000

    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000
