http:
  routers:
    todo-app:
      rule: PathPrefix(`/`)
      service: todo-app
      middlewares:
        - env-middleware

    todo-api:
      rule: PathPrefix(`/todos`)
      service: todo-api
      middlewares:
        - cors-middleware
        - env-middleware

    centrifugo:
      rule: PathPrefix(`/connection`)
      service: centrifugo

    grafana:
      rule: PathPrefix(`/grafana`)
      service: grafana

  services:
    todo-app:
      loadBalancer:
        servers:
          - url: http://todo-app

    todo-api:
      loadBalancer:
        servers:
          - url: http://todo-api

    centrifugo:
      loadBalancer:
        servers:
          - url: http://centrifugo:8000

    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000

  middlewares:
    cors-middleware:
      headers:
        accessControlAllowMethods: "*"
        accessControlAllowOriginList: "*"
        accessControlAllowHeaders: "*"
        accessControlMaxAge: 100
        addVaryHeader: true

    env-middleware:
      plugin:
        envplugin:
          env: dev
