http:
  routers:
    todo-app:
      rule: PathPrefix(`/`)
      service: todo-app

    todo-api:
      rule: PathPrefix(`/todos`)
      service: todo-api

    centrifugo:
      rule: PathPrefix(`/connection`)
      service: centrifugo

    grafana:
      rule: PathPrefix(`/grafana`)
      service: grafana

  services:
    todo-app:
      loadBalancer:
        servers:
          - url: http://todo-app

    todo-api:
      loadBalancer:
        servers:
          - url: http://todo-api

    centrifugo:
      loadBalancer:
        servers:
          - url: http://centrifugo:8000

    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000
