tls:
  certificates:
    - certFile: /etc/traefik/certs/public.crt
      keyFile: /etc/traefik/certs/private.key

http:
  routers:
    todo-app:
      rule: Host(`www.hobbydemos.com`)
      service: todo-app
      tls: {}

    todo-api:
      rule: Host(`api.hobbydemos.com`)
      service: todo-api
      tls: {}
      middlewares:
        - cors-middleware

    centrifugo:
      rule: Host(`centrifugo.hobbydemos.com`)
      service: centrifugo
      tls: {}

    keycloak:
      rule: Host(`auth.hobbydemos.com`)
      service: keycloak
      tls: {}

    grafana:
      rule: Host(`grafana.hobbydemos.com`)
      service: grafana
      tls: {}

  services:
    todo-app:
      loadBalancer:
        servers:
          - url: http://todo-app

    todo-api:
      loadBalancer:
        servers:
          - url: http://todo-api

    centrifugo:
      loadBalancer:
        servers:
          - url: http://centrifugo:8000

    keycloak:
      loadBalancer:
        servers:
          - url: http://keycloak:8080

    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000

  middlewares:
    cors-middleware:
      headers:
        accessControlAllowMethods:
          - OPTIONS
          - GET
          - POST
        accessControlAllowOriginList:
          - https://www.hobbydemos.com
        accessControlAllowHeaders:
          - Authorization
          - Content-Type
        accessControlMaxAge: 100
        addVaryHeader: true
